### ISSUE TITLE
any readme?

### ISSUE THREAD

**Issue by asdfqwer2015** [ahmetgunduz/Real-time-GesRec#1]
Hi:
  Thanks for your shared code.
  But could you please write a readme?

**Comment by asdfqwer2015** [comment]
And I found online and offline sh scripts. The online one invoking `real_time_test` script seems only test the model. The offline one invoking `main` script seems only train a cls_model without det_model. So, how can I train a full steps model?
Thx.

**Comment by ahmetgunduz** [comment]
Hi,
The code is still in process. Sorry that it is taking time. I am still clearing up the staging code. Later today I will add the readme file. Regarding detector training you can use offline sh script as well but the model should be specified as resnenl and n_classes = 2 since it is a binary classifier  .

**Comment by ahmetgunduz** [comment]
I am closing this issue, if you have any other question please open a new one.

**Comment by asdfqwer2015** [comment]
Hi:
  thanks for your detailed reply. I'll try the n_classes=2 detector from offline script.
