### ISSUE TITLE
Variables in online_test.py

### ISSUE THREAD

**Issue by olgapeled** [ahmetgunduz/Real-time-GesRec#10]
Hi again,

Can you please give more details of some of the variables in online_test script?
I think that I understand them, but after looking at the code, I am not sure... 

1. passive_count => # consecutive number of 'no gesture' classifier
2. active
3. active_index 
4. pre_predict
5. finished_prediction
6. prev_active

There is a situation where finished_prediction = false but we got to the last window frame?
so, results is empty (predicted = np.array(results)[:, 1]) and the code is fails...
I am wondering how to deal with that? how to  calculate levenshtein_distance in this case?

Thank you again!!!!

**Comment by ahmetgunduz** [comment]
Hi, 

`passive_count` is a counter keeps the number of consecutive iterations you get no gesture class
`active` is the state either active (classifier is active) or not. 
`active_index` it is just the index number so that I can fed into weighting function. Think of this like x asis of the function 
`pre_predict` whether it is predicted early or not
`finished_prediction` when state goes from active to passive this parameter set is true. It triggers predict when gesture ends
`prev_active` state in the previous iteration. I use this to be able to detect the trasition of the `active` parameter

Are you using nvGesture dataset? If that is the case each video has only one gesture and sometimes it does not have `no gesture` frames at the end of video so you have to add some frames(I used 16) from the beginning of the data so that detector could have enough time to deactivate the classifier.  This is not included in the code since it is a spesific property of Nvidia Gesture dataset.
