### ISSUE TITLE
jester pretrained model

### ISSUE THREAD

**Issue by Omenranr** [ahmetgunduz/Real-time-GesRec#21]
Hello, you did a great work good job !
My question is about the jester resnext pretrained weights:
1) I want to know given for exampe a single folder with 35 RGB frames what are the transformations that I need to make to this frames to get the right input and then make prediction ?
2) And how I can load the resnext model properly ?
3) And is the pretrained weights compatible with pytorch 1.0.1 cuda 10

**Comment by ahmetgunduz** [comment]
Hi @Omenranr ,
Sorry for late reply, I have been really busy these days. 

1. There are two kinds of transformations needs to be done: a) Temporal and b) Spatial. Temporal transformation is for getting right amount of frames in right order.  On the other hand, spatial transformation is done to get the input image shape (width and height) right. Both has augmentation methods as well **but it is only for training**. You are interested only in inference I believe. In this case, you would need to follow the same transformation in https://github.com/ahmetgunduz/Real-time-GesRec/blob/cec7050b3cea2d3ec33967a1552d2022b89d4166/offline_test.py#L100-L106

2. Please follow the https://github.com/ahmetgunduz/Real-time-GesRec/README.md and run_offline.sh has an example. 

3. It is since it is pytorch base object (`torch.Tensor`)

Best,
Ahmet

**Comment by Omenranr** [comment]
Thank you Ahmed for your answer even though I already figured out how to do it xD.
