### ISSUE TITLE
Start frame and end frame missing from trainlist01.txt and vallist01.txt.

### ISSUE THREAD

**Issue by funghan** [ahmetgunduz/Real-time-GesRec#32]
In README.md it says that N frames format is as following: "path to the folder" "class index" "start frame" "end frame".
However that information seems to be missing from annotation_Jester/trainlist01.txt and annotation_Jester/vallist01.txt. Is it somewhere else? Am I looking at the right files?

Thanks.

**Comment by ahmetgunduz** [comment]
Hi @funghan , 

You are definitely right, but it should work for jester since this is considered in https://github.com/ahmetgunduz/Real-time-GesRec/blob/cec7050b3cea2d3ec33967a1552d2022b89d4166/datasets/jester.py#L46-L58 
. Also in jester the start end frame are not needed since we have each video already cropped.

**Comment by funghan** [comment]
Hi @ahmetgunduz,
Noted about it being handled in code.

For quite a number of videos, there are frames at the beginning and end that are not part of the actual gesture, i.e. can be classified as No_gesture. Will this not affect the training?

**Comment by ahmetgunduz** [comment]
Unfortunately yes, that will affect the training. This is also the case for nvGesture but the staret end end frames of these dataset were not provided.

**Comment by funghan** [comment]
Thanks for the info.
