### ISSUE TITLE
Explanation of Testing

### ISSUE THREAD

**Issue by mhsattarian** [ahmetgunduz/Real-time-GesRec#8]
Hey Ahmet,
thanks for this amazing work.

I was going to test your pretrained model but there are a lot of disambiguations! can you please explain how, or give an instruction on running and testing your model?

**Comment by mhsattarian** [comment]
for example what is the difference between `run_online` and `run_offline` scripts?

**Comment by ahmetgunduz** [comment]
Hi @mhsattarian,
Thanks for kinds comments and well explained questions. You are right, I should have explained offline and online testing in more details. 

> what is the difference between `run_online` and `run_offline` scripts?
**run online** is for real-time analysis. It has different data loading methods as slide through the frames and make predictions in real time simulation environment. It runs `online_test.py`, in which the real-time detection and classification algorithms are implemented as it is described in the article.
**run offline**, on the other hand, is for training and evaluation of the models on the predefined clips of videos. This is the usual way of training a model. When you want to train a model for a dataset you need to train them first **offline** and then if you want to see their performance on a real-time scenario you would use `run_online` script by giving pretrained path, which is also depends either detector or classifier. 

> what changes should be applied to these scripts parameters in order to just test your model on a video?

 As an example I am giving offline testing. But you can also do the same for online testing by providing two architecture paths (detector and classifier). SO the followings are for `run_offline.sh`

First you need to run `offline_test.py`instead of `main.py`, which is for training.
_for dataset configurations_ (the followings are based on my path configurations for Egogesture dataset):
```bash
--root_path ~/ \
--video_path /data2/EgoGesture/images \
--annotation_path ~/Real-time-GesRec/annotation_EgoGesture/egogesturebinary.json\
```

_for pretrained path configuration_:
```bash
--resume_path MyRes3D-Ahmet/report/egogesture_resnetl_10_Depth_8_9939.pth \
-dataset egogesture \
--sample_duration 8 \
--model resnetl \
--model_depth 10 \
--batch_size 8 \
--n_classes 2 \ # if it is detector 2, if classifier # of classes in that dataset
--n_finetune_classes 2 \ # if it is detector 2, if classifier # of classes in that dataset
--modality Depth \
```
my pretrained model's names are in following convention <dataset>_<model>_<model_depth>_<modality>_<sample_duration>.pth

> why run_offline script calls model.py instead of offline_test.py?

I believe you meant `main.py`. `main.py` is for training, `offline_test.py` is for testing.


> why there is no pretrain_path_det and pretrain_path_clf defined in run_online or run_offline scripts? aren't pretrained weights needed in order to test the model?

pretrain_path_<det or clf> is fr detector and classifier  architecture paths
 and they are defined only for online testing. Because in online testing, it used detector and classifier together, However for offline training and testing you do this process seperately, and you can only use pretrained_path in for those. 

Hope this is clear. If not you may check the paper again, because it may be a little confusing  to distinguis between offline and online is important here. As a last note, Offline is for training models and make them ready for onlline (real-time) testing. 

Please let me know if this works for you.

**Comment by mhsattarian** [comment]
thank you @ahmetgunduz for answering all of the questions in detail.

**Comment by ahmetgunduz** [comment]
you are welcome! @mhsattarian
