### ISSUE TITLE
Miss alarm when same gesture twice in online mode?

### ISSUE THREAD

**Issue by asdfqwer2015** [ahmetgunduz/Real-time-GesRec#9]
Hi, ahmetgunduz:
  I tested the model in online mode with my own video. And all looks fine except if I show the same gesture twice. The model failed to predict the second gesture(no gesture is detected). And I doubt the reason maybe the rule based filter, but I'm not sure. Could you please give me some advice?

**Comment by ahmetgunduz** [comment]
Hi @asdfqwer2015,

It is probably the rule based filter as you said; however, it is enabled during the classifier architecture is in active state. In other words, there must be some frames that detector predicts no gesture in order to deactivate classifier, So when you were performing two gestures one after another, get your hand out of the camera view for some time. If this works for you then, probably the detector architecture is not working well. 

Did you train your own models or the pretrained ones?

**Comment by asdfqwer2015** [comment]
Hi,ahmetgunduz:
Thanks for your reply.
I trained the model with jester(eval acc > 92%) and tested on my own video.
I dug into this miss alarm case and checked the `online_test.py` script and found if the same gesture(with no_gesture separation) were detected then for the second gesture(assume cum_sum[best1] > clf_thresh_final):
1. if pre_predict, it can be detected only if `best1 != prev_best1`, this is False, so it comes a missed gesture
2. if late predict:
  a. if `best1 == prev_best1`, `cum_sum[best1] > 5` checking and we'll get a late detected gesture
  b. if `best1 != prev_best1`, we'll get a late detected gesture

I'm still validating this case and not very sure about this, but I doubt if we get the same gesture with high conf early detecting, we may miss the last one.

**Comment by ahmetgunduz** [comment]
Hi, 

Honestly, If I had more time, I would definitely add a hypothesis testing here instead of a rule based thresholds. You are definitely right! It is possible that you miss a gesture here, and yours is probably because of the 1st item you mentioned.  

> 
    if pre_predict, it can be detected only if best1 != prev_best1, this is False, so it comes a missed gesture
   
You need to choose between how early you want to detect a gesture and how much Levenshtein accuracy. As you decreased the `clf_threshold_pre` you will get earlier detection but lose accuracy exactly because of the scenario you confront.

This comes with a strong assumption, which is between each gesture detector architecture **must** deactivate the classifier.

Any suggestion for this is welcome here!

**Comment by asdfqwer2015** [comment]
Hi:
Here are my experiment details:
net: RexNeXt101
cls: 27 cls(include `no_gesture`)
prec@1: 0.948
prec@5: 0.997
precision: 0.91397
recall: 0.91336
I treat `no_gesture` and `something_else` as neg gestures, and others 25 gestures as pos gestures, det and cls by the same model and inference once per frame, cls only if det result in pos gestures.

And I have not tested, but if use a new threshold likes https://github.com/ahmetgunduz/Real-time-GesRec/blob/225ec81e97ba09849b5457a98d4ddad00176a50c/online_test.py#L323 instead of  https://github.com/ahmetgunduz/Real-time-GesRec/blob/225ec81e97ba09849b5457a98d4ddad00176a50c/online_test.py#L316 to handle same pre-detected gesutes, is it available?

**Comment by ahmetgunduz** [comment]
HI, 
I would check the models ability in detecting  gesture `pos gestures` against `neg gestures` before whether using it as a detector as well. Also if you are using the same architecture as cls and det, there is no need to use detector  + classifier hierarchical setup. THis is because, you get the prediction of the models twice and there is no need for that. If I were you , I would train a simpler architecture (like resnetl) for a binary detection of gestures, `GESTURE` or `NO_GESTURE`. Then it makes sense. 

Regarding the threshold, you can do that easily by changing the if else statement under pre_predict case. But I do not think it will not be easy to find the optimum threshold and probably it will not perform better. I have tried many different scenarios for this rule-based part and current one was the best I found.

**Comment by asdfqwer2015** [comment]
Thanks for your reply with details again.
Thanks for your advice, I'll train a detector  to decrease device's calc burden with `no person` and `no gesture` scenes. But currently, the model has no need to inference twice, the neg(`no person` and `no gesture`) and pos gestures will be predicted as the same inference step, and if sum of neg cls probs less than thresh, the virtual classifier will use the pos probs without inference again. Any way, the most scenes are neg cls, so I should train a detector.

**Comment by asdfqwer2015** [comment]
And Could you please share some params about your shared trained model? normalization settings and etc.
Thanks.

**Comment by ahmetgunduz** [comment]
HI @asdfqwer2015 ,  I kept everything as default except the paths, and model parameters.

**Comment by asdfqwer2015** [comment]
Thanks, ahmetgunduz.
I've no more questions about this issue. If you want, this issue could be closed.
:)

**Comment by ahmetgunduz** [comment]
👍

**Comment by manish2295** [comment]
> Hi, ahmetgunduz:
> I tested the model in online mode with my own video. And all looks fine except if I show the same gesture twice. The model failed to predict the second gesture(no gesture is detected). And I doubt the reason maybe the rule based filter, but I'm not sure. Could you please give me some advice?

@asdfqwer2015 Can you explain how you tested your video on the pretrained model?

**Comment by asdfqwer2015** [comment]
@manish2295
  I've only tested my video with my trained model with jester 27 classes with acc > 92%, I've not tested pretrained model from ahmetgunduz. 
  I borrowed rules from https://github.com/ahmetgunduz/Real-time-GesRec/blob/225ec81e97ba09849b5457a98d4ddad00176a50c/online_test.py and I tested 2 different gestures, each gesture 2 times. But the result is that the second time for each gesture has not been detected. While debugging, it seems like all actions have been detected as early detection, but ignored by https://github.com/ahmetgunduz/Real-time-GesRec/blob/225ec81e97ba09849b5457a98d4ddad00176a50c/online_test.py#L316
